### ISSUE TITLE
Kailhロープロファイルだとアクリルケース邪魔でキーキャップが設置出来ない

### ISSUE THREAD

**Issue by t10471** [kata0510/Lily58#1]
Kailhロープロファイル対応と書いてあると思うのですが、
遊舎工房さんで買った `Kailhロープロファイルスイッチ` と `Kailhロープロ無刻印(遊刻印)キーキャップ` だとキーの高さに対して上のアクリルケースが邪魔でキーキャップが設置出来ません。
Kailhロープロファイル用のアクリルケースとスペーサーが欲しいです。

**Comment by kata0510** [comment]
キット販売で使用している部品を使用して検証したところこちらの環境ではロープロファイルスイッチとキーキャップはProMicro上部のアクリル部には干渉しませんでした。
お手数ですが干渉している部分の写真を添付してくださると修正対応等ができますのでよろしくおねがいします。
![img_8800](https://user-images.githubusercontent.com/6285554/47604611-1ed2fb80-da37-11e8-9c3a-fe691d82ba65.JPG)
![img_6420](https://user-images.githubusercontent.com/6285554/47604612-1ed2fb80-da37-11e8-9efa-7faca00748f5.JPG)

**Comment by t10471** [comment]
これがはめた画像です。
![image](https://user-images.githubusercontent.com/424405/47605501-192ee300-da42-11e8-9ee6-da53d9a92ee4.png)

遊舎工房さんで(https://yushakobo.jp/shop/pg1350/) 買ったものだと、
アクリルケースの穴よりちょっと大きい気がします...
![image](https://user-images.githubusercontent.com/424405/47605534-c99ce700-da42-11e8-9254-89f56b98274a.png)

**Comment by kata0510** [comment]
写真を見させていただいたところ組み立て方に間違いがあるようです。
ロープロファイルの場合PCBとスイッチをマウントするアクリルの間に隙間が生まれないためダイオードは**裏側に**はんだ付けをする必要があります。
スイッチをアクリルに取り付けるにはコツがありますが斜めの状態でスイッチ側面の爪の部分を押し込むと取り付けられるかと思います。
この場合ですと一旦スイッチのはんだ付けをすべて外し、ダイオードが裏側に来るように左右のPCBを逆にしてからスイッチをアクリルに取り付けてサイドはんだ付けを行う必要があります。

**Comment by t10471** [comment]
なるほど、、、もう一セット買おうかと思います。。。

**Comment by kata0510** [comment]
半田吸い取り線でスイッチを取り外して正しく組み直せば十分対処できる範囲かと思います。また何か質問などあればTwitterにて対応出来ますのでよろしくお願いします。
