### ISSUE TITLE
Lily58 Pro case sizes

### ISSUE THREAD

**Issue by IgorLGMS** [kata0510/Lily58#11]
Hi and thank you for your work and dedication to the keyboard community!

I contacted a laser cutting company to cut a Lily 58 pro case, but they replied that the files I gave them didn't have any sizes on them, what are the correct sizes to cut that plates?

Or what is the correct way to get the plates cut?

**Comment by kata0510** [comment]
Hi!
Use this data when cutting acrylic cases
https://github.com/kata0510/Lily58/blob/master/case/Lily58_case.ai

The case file in the directory of Lily58 Pro is used to make a case with FR-4

**Comment by IgorLGMS** [comment]
Oh ok, thank you!
