### ISSUE TITLE
Using "only one" Lily58 as a Macropad

### ISSUE THREAD

**Issue by Ferryistaken** [kata0510/Lily58#12]
I would like to know if I will be able to use only "one" lily58 pcb and pro micro as a macropad/numpad using qmk, to then in the future order also the second pcb and microcontroller to make it a full keyboard. Will I be able to do this or do I need both microcontrollers and pcbs to use the lily58?

**Comment by BenRoe** [comment]
You can use one half without a problem.

**Comment by Ferryistaken** [comment]
One more question, What is the difference between the normal and the pro?

**Comment by kata0510** [comment]
The difference between Pro and Normal (Lite) is hot swap support
