### ISSUE TITLE
For the English Build Guide Could You Add Flash Both Pro Micros Individually?

### ISSUE THREAD

**Issue by StarWhiz** [kata0510/Lily58#17]
Mentioned Guide: https://github.com/kata0510/Lily58/blob/master/Pro/Doc/buildguide_en.md

When I was first building this board. I flashed both sides by accident. Then only flashed changes to keymap on the left side. 

I was wondering why the lily58 keymap with encoder causes the right side to fail and not register keystrokes. When I removed encoder code from keymap it would work.

After hours of troubleshooting, it turns out all I needed to do is flash encoder keymap to both pro micros individually. Now encoder and right side works as well!

Newbies may get stuck at this not knowing that whatever they flash to one side they have to flash to the other in order to ensure everything works!

**Comment by kata0510** [comment]
This English build guide is based on Lily58 Pro, which is available in Japan.
There is a Lily58 Pro PCB available outside of Japan that can be used with the encoder, but I don't have the PCB so I can't support it. 
Consult the distributor. sorry.
