### ISSUE TITLE
bad pcb tracing

### ISSUE THREAD

**Issue by heartpolik** [kata0510/Lily58#21]
have an gap at this place
http://joxi.ru/823vQjec8aBzNm
http://joxi.net/zAN6l5ZTj8qw8A

**Comment by kata0510** [comment]
Open in Kicad and there is no problem
![スクリーンショット 2020-11-30 13 25 37](https://user-images.githubusercontent.com/6285554/100568869-b76f9000-330f-11eb-894a-439f55b11c80.png)
![スクリーンショット 2020-11-30 13 25 52](https://user-images.githubusercontent.com/6285554/100568873-ba6a8080-330f-11eb-9703-0dca73c695cb.png)

**Comment by japko** [comment]
I just want to leave a comment for people having same issue.

![badtrace](https://github.com/kata0510/Lily58/assets/2715489/6e92e14f-b6e4-4df8-8256-87abbf6f9054)



Debugging this was a nightmare. I'm not so skilled in soldering so I assumed this was my fault ;-)

I ordered PCB at jlcpcb.com
