### ISSUE TITLE
Problems with the gerber files (non pro lily58)

### ISSUE THREAD

**Issue by caileighf** [kata0510/Lily58#3]
Hi! I tried to order the PCBs from a fab shop I've used before but it looks like the gerber only has the copper traces. Would you be willing to upload gerbers with all the necessary layers? Or if you could let me know how it's supposed to be done in KiCad if that's were you designed it. I really love the board you've made.
![Screen Shot 2019-04-26 at 10 56 12 AM](https://user-images.githubusercontent.com/25257452/56816644-f4110680-6811-11e9-8e8d-eaf2e360a086.png)

**Comment by kata0510** [comment]
Please plot the file with the setting suitable for the PCB factory by the procedure of File-> Plot
The uploading Gerber is for elecrow
thanks!
![スクリーンショット 2019-05-06 16 10 52](https://user-images.githubusercontent.com/6285554/57211076-f34e5080-7019-11e9-85c1-6f52b375cf5d.png)
![スクリーンショット 2019-05-06 16 10 56](https://user-images.githubusercontent.com/6285554/57211079-f47f7d80-7019-11e9-9fb4-53a1f434a505.png)
![スクリーンショット 2019-05-06 16 11 15](https://user-images.githubusercontent.com/6285554/57211082-f8130480-7019-11e9-8a06-f6075d7e3de5.png)

**Comment by caileighf** [comment]
This is great! Thank you for the instructions.
