### ISSUE TITLE
using type-c to type-c connect to pc, no power...

### ISSUE THREAD

**Issue by gshmu** [kata0510/Lily58#39]
Can not connect the computer directly with the double-headed type-c, and the keyboard is no power.

**Comment by kata0510** [comment]
This is not a Lily58 problem, but a ProMicro problem.
ProMicro without CC1 and CC2 pull-downs on the Type-C connector cannot use C to C cables.

**Comment by gshmu** [comment]
Thank you very much @kata0510 .
I tried  my friends claw44, it connect with C to C cables well. Is the cables differently?

**Comment by kata0510** [comment]
Is it the same ProMicro and the same cable?
